apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    template: prune-tekton-pipelinerun
  name: {{ .Values.namespace }}-tekton-pipelinerun-pruners
roleRef:
  apiGroup: rbac.authorization.k8s.io
  name: cluster-admin
  kind: ClusterRole
subjects:
- kind: ServiceAccount
  name: {{ .Values.job_service_account }}
  namespace: {{ .Values.namespace }}