kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: deployment-pruner
rules:
- apiGroups:
  - ""
  - apps.openshift.io
  resources:
  - deploymentconfigs
  verbs:
  - get
  - list
  - delete
- apiGroups:
  - ""
  - apps.openshift.io
  resources:
  - deployments
  verbs:
  - get
  - list
  - delete
- apiGroups:
  - ""
  resources:
  - replicationcontrollers
  verbs:
  - get
  - list
  - delete