---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: jaeger-product
  namespace: openshift-operators
  annotations:
      argocd.argoproj.io/sync-wave: "15"
spec:
  channel: stable
  installPlanApproval: Manual
  name: jaeger-product
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: jaeger-operator.v1.28.0
