kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: build-pruner
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
rules:
- apiGroups:
  - ""
  - build.openshift.io
  resources:
  - buildconfigs
  verbs:
  - get
  - list
- apiGroups:
  - ""
  - build.openshift.io
  resources:
  - builds
  verbs:
  - get
  - list
  - delete