apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-config-manager
  labels:
    gitops.ownedBy: cluster-config
spec:
  destination:
    namespace: openshift-gitops
    server: https://kubernetes.default.svc
  project: cluster-config
  source:
    path: clusters/overlays/sanbox-cluster/argocd/apps
    repoURL: https://github.com/sampop3/gitops-demo.git
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
