---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: servicemesh-operator
  namespace: openshift-operators
  annotations:
      argocd.argoproj.io/sync-wave: "15"
spec:
  channel: stable
  installPlanApproval: Manual
  name: servicemeshoperator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: servicemeshoperator.v2.1.2.1