apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prune-tekton-pipelineruns-job
  annotations:
    argocd.argoproj.io/sync-wave: "30"
  labels:
    repo: local
spec:
  destination:
    server: https://kubernetes.default.svc
  project: infra-jobs
  source:
    path: manifests/configs/openshift-prune-tekton-pipelinerun-job
    repoURL: https://github.com/sampop3/gitops-demo.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
