apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openshift-servicemesh-operator
  annotations:
    argocd.argoproj.io/sync-wave: "33"
  labels:
    repo: local
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    path: manifests/configs/openshift-servicemesh-operator/base
    repoURL: https://github.com/sampop3/gitops-demo.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
